"""Guess the Elo Duels — head-to-head rating-guessing game.

Two players are shown the *same* game (generated by Maia-2 self-play at a hidden
true rating) and have two minutes to guess that rating; the closest guess wins.

Layering (mirrors ``server/modes.py``):

* **Pure logic** — ``decide_winner``, ``guess_points``, ``bot_guess`` — no I/O,
  unit-tested.
* **Data access** — the ``elo_games`` pool and ``elo_duels`` records.
* **Matchmaking** — an in-process waiting room that pairs two humans when both
  are searching, and falls back to a Maia-2 *bot* opponent after a short wait so
  a duel is always available (essential for a live demo).

Game generation (:func:`generate_elo_game`) needs a Maia-2 policy and is run
offline to populate the pool (see ``scripts``); everything else is engine-free.
"""

from __future__ import annotations

import io
import random
import sqlite3
import threading
import time
from dataclasses import dataclass

import chess
import chess.pgn

# Maia-2's coherent rating range — the hidden true ratings we generate at.
ELO_POOL: tuple[int, ...] = (1100, 1300, 1500, 1700, 1900)
GUESS_MIN = 600
GUESS_MAX = 2600
DUEL_SECONDS = 120
BOT_WAIT_SECONDS = 6.0
# A waiting ticket older than this is considered abandoned.
WAIT_STALE_SECONDS = 20.0


# --------------------------------------------------------------------------- #
# Pure scoring                                                                  #
# --------------------------------------------------------------------------- #


def clamp_guess(value: int) -> int:
    return max(GUESS_MIN, min(GUESS_MAX, int(value)))


def guess_points(true_elo: int, guess: int | None) -> int:
    """0–100 accuracy points for a single guess; smooth decay with error.

    100 for a bullseye, ~61 at 100 off, ~14 at 400 off, 0 for no guess.
    """
    if guess is None:
        return 0
    import math

    return round(100.0 * math.exp(-abs(int(true_elo) - int(guess)) / 200.0))


def decide_winner(true_elo: int, guess_a: int | None, guess_b: int | None) -> str:
    """Return ``"a"`` / ``"b"`` / ``"draw"`` — closest guess to ``true_elo`` wins.

    A missing guess always loses to a present one; two missing guesses draw.
    """
    if guess_a is None and guess_b is None:
        return "draw"
    if guess_a is None:
        return "b"
    if guess_b is None:
        return "a"
    da, db = abs(true_elo - guess_a), abs(true_elo - guess_b)
    if da < db:
        return "a"
    if db < da:
        return "b"
    return "draw"


def bot_guess(true_elo: int, rng: random.Random, *, sigma: float = 220.0) -> int:
    """A competitive-but-beatable bot guess: Gaussian noise around the truth,
    rounded to the nearest 50 and clamped to the legal range."""
    raw = rng.gauss(true_elo, sigma)
    return clamp_guess(int(round(raw / 50.0) * 50))


# --------------------------------------------------------------------------- #
# Game generation (Maia-2 self-play) — offline pool builder                     #
# --------------------------------------------------------------------------- #


def _sample_move(
    board: chess.Board,
    dist: dict,
    legal: list,
    rng: random.Random,
    *,
    temperature: float,
    top_k: int,
    recent: set,
    undo: tuple,
    recent_from: set,
) -> object:
    """Sample from the policy over the top-``k`` moves, taming the shuffling that
    pure Maia sampling produces at low ratings (it reads as a broken generator).

    Guards: a move that reverses this side's own previous move (``undo``) is
    nearly forbidden; a move landing on a **recently-vacated square**
    (``recent_from`` — the whole knight-shuffle family) is strongly downweighted;
    and a move recreating a recent board placement is downweighted.
    """
    if not dist:
        return rng.choice(legal)
    ranked = sorted(legal, key=lambda m: dist.get(m, 0.0), reverse=True)[:top_k]
    weights: list[float] = []
    for move in ranked:
        w = max(0.0, float(dist.get(move, 0.0))) ** (1.0 / max(0.05, temperature))
        if move.from_square == undo[0] and move.to_square == undo[1]:
            w *= 0.001
        if move.to_square in recent_from:
            w *= 0.08
        board.push(move)
        repeats = board.board_fen() in recent
        board.pop()
        if repeats:
            w *= 0.02
        weights.append(w)
    if sum(weights) <= 0.0:
        return ranked[0] if ranked else rng.choice(legal)
    return rng.choices(ranked, weights=weights, k=1)[0]


def generate_elo_game(
    policy: object,
    elo: int,
    *,
    rng: random.Random,
    max_plies: int = 60,
    temperature: float = 0.8,
    top_k: int = 8,
) -> tuple[str, int]:
    """Play a full game with Maia-2 at ``elo`` on both sides, moves sampled from
    the policy (top-k trims only the degenerate tail; ``temperature`` ~1 keeps
    human variety and, importantly, longer meandering games). Returns
    ``(pgn, plies)``.
    """
    from collections import deque

    board = chess.Board()
    game = chess.pgn.Game()
    game.headers["Event"] = "Guess the Elo Duel"
    game.headers["White"] = f"Maia-{elo}"
    game.headers["Black"] = f"Maia-{elo}"
    node: chess.pgn.GameNode = game
    recent: deque = deque([board.board_fen()], maxlen=6)
    recent_from: deque = deque(maxlen=5)
    last_move: dict = {chess.WHITE: None, chess.BLACK: None}

    for _ in range(max_plies):
        if board.is_game_over(claim_draw=True):
            break
        legal = list(board.legal_moves)
        dist = policy(board.fen(), elo, legal)  # {move: prob}
        color = board.turn
        prev = last_move[color]
        undo = (prev.to_square, prev.from_square) if prev is not None else (None, None)
        move = _sample_move(
            board, dist, legal, rng,
            temperature=temperature, top_k=top_k,
            recent=set(recent), undo=undo, recent_from=set(recent_from),
        )
        last_move[color] = move
        recent_from.append(move.from_square)
        board.push(move)
        recent.append(board.board_fen())
        node = node.add_variation(move)

    exporter = chess.pgn.StringExporter(headers=True, variations=False, comments=False)
    pgn = game.accept(exporter)
    return pgn, board.ply()


def store_game(conn: sqlite3.Connection, true_elo: int, pgn: str, plies: int) -> int:
    cur = conn.execute(
        "INSERT INTO elo_games (true_elo, pgn, plies) VALUES (?, ?, ?)",
        (int(true_elo), pgn, int(plies)),
    )
    conn.commit()
    return int(cur.lastrowid)


def pool_size(conn: sqlite3.Connection) -> int:
    return int(conn.execute("SELECT COUNT(*) FROM elo_games").fetchone()[0])


def generate_and_store_pool(
    conn: sqlite3.Connection,
    policy: object,
    *,
    per_elo: int = 5,
    elos: tuple[int, ...] = ELO_POOL,
    seed: int = 0,
    on_game: object | None = None,
) -> int:
    """Populate ``elo_games`` with ``per_elo`` self-play games at each Elo."""
    rng = random.Random(seed)
    made = 0
    for elo in elos:
        for _ in range(per_elo):
            # Retry a few times so a quick decisive game (too short to guess
            # from) doesn't land in the pool; keep the last attempt regardless.
            for attempt in range(6):
                pgn, plies = generate_elo_game(policy, elo, rng=rng)
                if plies >= 24 or attempt == 5:
                    break
            store_game(conn, elo, pgn, plies)
            made += 1
            if callable(on_game):
                on_game(elo, plies, made)
    return made


# --------------------------------------------------------------------------- #
# Duel data access                                                              #
# --------------------------------------------------------------------------- #


def pick_random_game(
    conn: sqlite3.Connection, rng: random.Random | None = None, *, min_plies: int = 20
) -> sqlite3.Row | None:
    """A random pool game long enough to guess from, falling back to any game."""
    row = conn.execute(
        "SELECT * FROM elo_games WHERE plies >= ? ORDER BY RANDOM() LIMIT 1",
        (int(min_plies),),
    ).fetchone()
    if row is not None:
        return row
    return conn.execute("SELECT * FROM elo_games ORDER BY RANDOM() LIMIT 1").fetchone()


def create_duel(
    conn: sqlite3.Connection,
    game: sqlite3.Row,
    *,
    player_a: int,
    player_b: int | None,
    is_bot: bool,
    now: float,
    rng: random.Random,
) -> int:
    """Create an active duel. A bot opponent's guess is drawn now and stored as
    ``guess_b`` (revealed only at resolution)."""
    guess_b = bot_guess(int(game["true_elo"]), rng) if is_bot else None
    cur = conn.execute(
        """
        INSERT INTO elo_duels
            (game_id, true_elo, player_a, player_b, is_bot, guess_b, deadline_ts, status)
        VALUES (?, ?, ?, ?, ?, ?, ?, 'active')
        """,
        (
            int(game["id"]),
            int(game["true_elo"]),
            int(player_a),
            player_b,
            1 if is_bot else 0,
            guess_b,
            int(now + DUEL_SECONDS),
        ),
    )
    conn.commit()
    return int(cur.lastrowid)


def get_duel(conn: sqlite3.Connection, duel_id: int) -> sqlite3.Row | None:
    return conn.execute("SELECT * FROM elo_duels WHERE id = ?", (int(duel_id),)).fetchone()


def active_duel_for(conn: sqlite3.Connection, user_id: int) -> sqlite3.Row | None:
    return conn.execute(
        """
        SELECT * FROM elo_duels
        WHERE status = 'active' AND (player_a = ? OR player_b = ?)
        ORDER BY id DESC LIMIT 1
        """,
        (int(user_id), int(user_id)),
    ).fetchone()


def side_of(duel: sqlite3.Row, user_id: int) -> str | None:
    if int(duel["player_a"]) == int(user_id):
        return "a"
    if duel["player_b"] is not None and int(duel["player_b"]) == int(user_id):
        return "b"
    return None


def submit_guess(
    conn: sqlite3.Connection, duel: sqlite3.Row, side: str, guess: int, now: float
) -> sqlite3.Row:
    column = "guess_a" if side == "a" else "guess_b"
    conn.execute(
        f"UPDATE elo_duels SET {column} = ? WHERE id = ?",
        (clamp_guess(guess), int(duel["id"])),
    )
    conn.commit()
    return maybe_resolve(conn, get_duel(conn, int(duel["id"])), now)


def maybe_resolve(conn: sqlite3.Connection, duel: sqlite3.Row, now: float) -> sqlite3.Row:
    """Resolve the duel once both guesses are in or the deadline has passed."""
    if duel["status"] != "active":
        return duel
    both_in = duel["guess_a"] is not None and duel["guess_b"] is not None
    expired = now >= int(duel["deadline_ts"])
    if not (both_in or expired):
        return duel
    winner = decide_winner(int(duel["true_elo"]), duel["guess_a"], duel["guess_b"])
    conn.execute(
        "UPDATE elo_duels SET status = 'done', winner = ? WHERE id = ?",
        (winner, int(duel["id"])),
    )
    conn.commit()
    return get_duel(conn, int(duel["id"]))


# --------------------------------------------------------------------------- #
# Matchmaking (in-process waiting room + bot fallback)                          #
# --------------------------------------------------------------------------- #


@dataclass
class _Waiter:
    since: float


_WAITING: dict[int, _Waiter] = {}
_WAITING_LOCK = threading.Lock()


def _clear_stale(now: float) -> None:
    for uid, waiter in list(_WAITING.items()):
        if now - waiter.since > WAIT_STALE_SECONDS:
            del _WAITING[uid]


def leave_queue(user_id: int) -> None:
    with _WAITING_LOCK:
        _WAITING.pop(int(user_id), None)


def find_or_create_match(
    conn: sqlite3.Connection,
    user_id: int,
    *,
    now: float | None = None,
    rng: random.Random | None = None,
) -> tuple[str, sqlite3.Row | None]:
    """Return ``("matched", duel)`` or ``("searching", None)``.

    Pairs the caller with another waiting human when possible; otherwise keeps
    them in the waiting room and, after :data:`BOT_WAIT_SECONDS`, starts a bot
    duel so play is never blocked.
    """
    now = time.time() if now is None else now
    rng = rng or random.Random()
    user_id = int(user_id)

    existing = active_duel_for(conn, user_id)
    if existing is not None:
        return "matched", existing

    with _WAITING_LOCK:
        _clear_stale(now)
        for other_id, waiter in list(_WAITING.items()):
            if other_id != user_id:
                del _WAITING[other_id]
                _WAITING.pop(user_id, None)
                paired = other_id
                break
        else:
            waited = now - _WAITING.setdefault(user_id, _Waiter(now)).since
            paired = None

    game = pick_random_game(conn, rng)
    if game is None:
        return "searching", None  # empty pool — nothing to play yet

    if paired is not None:
        duel_id = create_duel(
            conn, game, player_a=paired, player_b=user_id, is_bot=False, now=now, rng=rng
        )
        return "matched", get_duel(conn, duel_id)

    if waited >= BOT_WAIT_SECONDS:
        leave_queue(user_id)
        duel_id = create_duel(
            conn, game, player_a=user_id, player_b=None, is_bot=True, now=now, rng=rng
        )
        return "matched", get_duel(conn, duel_id)

    return "searching", None


# --------------------------------------------------------------------------- #
# Serialization                                                                 #
# --------------------------------------------------------------------------- #


def game_moves_san(pgn: str) -> list[str]:
    """SAN move list for the frontend board replay."""
    game = chess.pgn.read_game(io.StringIO(pgn))
    if game is None:
        return []
    board = game.board()
    out: list[str] = []
    for move in game.mainline_moves():
        out.append(board.san(move))
        board.push(move)
    return out


def duel_public(
    conn: sqlite3.Connection, duel: sqlite3.Row, user_id: int
) -> dict[str, object]:
    """Serialize a duel for its participant. The true rating and the opponent's
    guess are only revealed once the duel is ``done``."""
    side = side_of(duel, user_id)
    game = conn.execute(
        "SELECT pgn, plies FROM elo_games WHERE id = ?", (int(duel["game_id"]),)
    ).fetchone()
    my_guess = duel["guess_a"] if side == "a" else duel["guess_b"]
    opp_guess = duel["guess_b"] if side == "a" else duel["guess_a"]
    done = duel["status"] == "done"
    payload: dict[str, object] = {
        "duel_id": int(duel["id"]),
        "you": side,
        "status": duel["status"],
        "deadline_ts": int(duel["deadline_ts"]),
        "is_bot": bool(duel["is_bot"]),
        "opponent": "Bot" if duel["is_bot"] else "Opponent",
        "pgn": game["pgn"] if game else "",
        "moves": game_moves_san(game["pgn"]) if game else [],
        "your_guess": my_guess,
        "opponent_guessed": opp_guess is not None,
        "guess_min": GUESS_MIN,
        "guess_max": GUESS_MAX,
    }
    if done:
        winner_side = duel["winner"]
        outcome = "draw" if winner_side == "draw" else ("win" if winner_side == side else "loss")
        payload.update(
            {
                "true_elo": int(duel["true_elo"]),
                "opponent_guess": opp_guess,
                "winner": winner_side,
                "outcome": outcome,
                "your_points": guess_points(int(duel["true_elo"]), my_guess),
                "opponent_points": guess_points(int(duel["true_elo"]), opp_guess),
            }
        )
    return payload


__all__ = [
    "BOT_WAIT_SECONDS",
    "DUEL_SECONDS",
    "ELO_POOL",
    "GUESS_MAX",
    "GUESS_MIN",
    "active_duel_for",
    "bot_guess",
    "clamp_guess",
    "create_duel",
    "decide_winner",
    "duel_public",
    "find_or_create_match",
    "game_moves_san",
    "generate_and_store_pool",
    "generate_elo_game",
    "get_duel",
    "guess_points",
    "leave_queue",
    "maybe_resolve",
    "pick_random_game",
    "pool_size",
    "side_of",
    "store_game",
    "submit_guess",
]
